### ISSUE TITLE
Inconsistent spacing of punctuation between fonts

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#100]
_This issue is likely related to the fix for [Issue 93](https://github.com/arnog/tecendil-js/issues/93)._

Commas, periods, etc in [DSS encoded fonts](https://www.tecendil.com/?q=%3A.%2C%3A.%2C&font=TengwarAnnatar) are spaced differently to [CSUR encoded fonts](https://www.tecendil.com/?q=%3A.%2C%3A.%2C&font=AlcarinTengwar); the former need to be manually spaced to match.

**Comment by arnog** [comment]
Fixed.
