### ISSUE TITLE
Looped sa-rince in Tengwar Artano

### ISSUE THREAD

**Issue by shankarsivarajan** [arnog/tecendil-js#103]
I see you've implemented a new font! Just fyi, the looped _sa_-rince hook _is_ available in the font but not mapped to a separate Unicode code-point. It may be created as a ligature of two regular _sa_-rinces, as documented in the font's [GitHub repo](https://github.com/shankarsivarajan/TengwarArtano).

**Comment by arnog** [comment]
I see... I have a single encoding for all the Unicode fonts, so I'm not sure how I'm going to handle this. I see that there is also an unexpected glyph at U+005C. The encoding is close, but doesn't match either https://www.evertype.com/standards/csur/tengwar.html or https://www.evertype.com/standards/iso10646/pdf/tengwar.pdf... Hmmm...

**Comment by arnog** [comment]
I've added a special encoding for Artano...
