### ISSUE TITLE
alt-esse-nuquerna bug

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#106]
In the site-relevant Dan-Smith-layout fonts, alt-esse-nuquerna is the less-than symbol… or opening angle bracket. You can probably already guess where this is going!

When immediately followed by certain characters the system gets tripped up and treats it as a new type of XML tag. This of course hides the esse and any following text till interrupted by a closing bracket (eg. by a break).

[Example](https://www.tecendil.com/?q=hello%0A%7Balt-esse-nuquerna%7Dgoodbye%0Ahello&font=TengwarAnnatar)

Hopefully the easiest fix will be to instead call the entity reference `&lt;`; though if that isn’t an option would wrapping the symbol in an empty span work?

**Comment by arnog** [comment]
Good catch. Converting to entity reference seems to work. Fixed now.
