### ISSUE TITLE
Westron Orthographic Q

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#107]
Westron Orthographic doesn’t have a rule for “q”, only “qu”.

[Example words](https://www.tecendil.com/?q=iraq%20qatar%20qi&mode=westron-orthographic)

The default English mode file sets it to just quesse; that seems reasonable.

When mode files give no results for input (e.g. “q” in Sindarin) should there be some indication?

**Comment by arnog** [comment]
Added the mapping for "q".
I'm not sure how to detect there are mappings "missing". It seems very dependent on the phonotactic inventory of the source language.
