### ISSUE TITLE
Literals with double letters break after space

### ISSUE THREAD

**Issue by feophan** [arnog/tecendil-js#108]
When using literals like [aara], [uure] or [thuule], if space character precedes it, the literal is not interpreted correctly.

![image](https://github.com/user-attachments/assets/42f6bebd-4b1e-4e74-a416-d51ec00a6e69)

With space removed it works:

![image](https://github.com/user-attachments/assets/0b8da5da-2e8d-4704-9220-69f8e8a5d404)

With a literal that doesn't have a double letter it works:

![image](https://github.com/user-attachments/assets/dfb81de5-9d19-4e62-944d-0a24b210c637)

**Comment by arnog** [comment]
Can you share a URL that shows the problem? It seems to work for me: https://www.tecendil.com/?q=t%20%5Buure%5D

**Comment by thirdofmarch** [comment]
I was curious so also had a look; this issue occurs when using one of the elvish modes.

[Example](https://www.tecendil.com/?q=a%20%5Baara%5D%20%5Buure%5D%20%5Bthuule%5D%0A%5Baara%5D%5Buure%5D%5Bthuule%5D%0Aa%20%7Baara%7D%20%7Buure%7D%20%7Bthuule%7D&mode=sindarin)

**Comment by feophan** [comment]
Modes in which the problem appears: German, Portuguese, Sindarin (both), Quenya.

**Comment by arnog** [comment]
Fixed and updated tecendil.com.
