### ISSUE TITLE
PR #17 : zh translations mixed mulitple languages and having severe localization issues

### ISSUE THREAD

**Issue by WinstonSung** [arnog/tecendil-js#18]
Split `zh` translations into

- `zh-Hans-CN`: `zh` - 简体中文 (Simplified Chinese)
- `zh-Hant-HK`: `zh-hk` - 港式繁體中文 (Hong Kong Traditional Chinese)
- `zh-Hant-TW`: `zh-tw` - 臺式繁體中文 (Taiwan Traditional Chinese)

as MediaWiki does and considered browser language code compatibility.

Pull Request: #17 - Fix keys, fix html p tag, split zh variants, fix part of the zh-Hans-CN, zh-Hant-HK and zh-Hant-TW translations

**Comment by WinstonSung** [comment]
Hello, Arno,

I would like to know is there any progress on this issue/pull request.

It seems you have made some changes in this repository, but didn't merge the pull request. Is there any you're concerning?

Please let me know. Thanks.

Sincerely,
Winston Sung

**Comment by arnog** [comment]
Thanks for filing this. I'm sorry for the lateness, I had somehow completely missed this. I have now merged the PR and pushed an update on Tecendil.com.

One question for you: the language menu in the Settings dialog now only include "簡體中文" which is mapped to the `zh` language code. Should the label for this be "简体中文" instead?

And should there be separate entries for 港式繁體中文 (Hong Kong Traditional Chinese) and 臺式繁體中文 (Taiwan Traditional Chinese)?

**Comment by WinstonSung** [comment]
> One question for you: the language menu in the Settings dialog now only include "簡體中文" which is mapped to the zh language code. Should the label for this be "简体中文" instead?

Yes, need to be corrected.

> And should there be separate entries for 港式繁體中文 (Hong Kong Traditional Chinese) and 臺式繁體中文 (Taiwan Traditional Chinese)?

Yes, need to be split.

**Comment by WinstonSung** [comment]
> **`zh` variants included in this file:**
> Using these codes is for browser compability.
> - `zh`: 简体中文 (Simplified Chinese)
> - `zh-hk`: 港式繁體中文 (Hong Kong Traditional Chinese)
> - `zh-tw`: 臺式繁體中文 (Taiwan Traditional Chinese)

**Comment by arnog** [comment]
OK, great, thanks for confirming. I have updated tecendil.com with those changes. Please don't hesitate to let me know if anything needs to be changed.

**Comment by WinstonSung** [comment]
`pl` haven't been added to language settings?

**Comment by WinstonSung** [comment]
Umm... it seems the language (browser detection) is somewhat broken.

accept-language: zh-TW,zh;q=0.9

**Comment by WinstonSung** [comment]
Does it have any kind of language code fallback system?

**Comment by arnog** [comment]
- `pl` has been added now
- there is a language code fallback (i.e. looks for `zh-TW`, then `zh` if no string found), but it was expecting a locale code in lowercase. I've fixed it now, let me know if this doesn't work.

**Comment by WinstonSung** [comment]
It works perfect now. Thanks.

**Comment by arnog** [comment]
Awesome. Thanks, and thank you again for your patience.
