### ISSUE TITLE
[Defect] i18n: Traditional Chinese languages use Simplified Chinese glyphs/fonts

### ISSUE THREAD

**Issue by WinstonSung** [arnog/tecendil-js#19]
Traditional Chinese languages use Simplified Chinese glyphs/fonts.

Traditional Chinese languages having the same class `lang-zh` which Simplified Chinese used. However, Simplified Chinese languages/variants and Traditional Chinese languages/variants use different font sets.

Simplified Chinese specific fonts:

> `'Microsoft YaHei New','Microsoft Yahei','微软雅黑',宋体,SimSun,STXihei,'华文细黑'`

Suggest separate `lang-zh` to `lang-zh-Hans` (for `zh`) and `lang-zh-Hant` (for `zh-hk` and `zh-tw`) and use below fonts for Traditional Chinese (replace Simplified Chinese fonts in Traditional Chinese specific css):

> `'Noto Sans CJK TC','Noto Sans TC','Noto Sans','Microsoft JhengHei UI','Microsoft JhengHei','微軟正黑體','Noto Serif CJK TC','Noto Serif TC','Noto Serif','新細明體','PMingLiU','細明體','MingLiU'`

And update Simplified fonts to:

> `'Noto Sans CJK SC','Noto Sans SC','Noto Sans','Microsoft YaHei New','Microsoft Yahei','微软雅黑','Noto Serif CJK SC','Noto Serif SC','Noto Serif',SimSun,'宋体',STXihei,'华文细黑'`

**Comment by arnog** [comment]
Thanks for the feedback. I've updated the font list and split it for traditional and simplified.

**Comment by WinstonSung** [comment]
Due to a bug for the accent display in 'Noto Sans CJK TC' and 'Noto Sans TC', please remove

> `'Noto Sans CJK TC','Noto Sans TC',`

from the list of fonts.

**Comment by arnog** [comment]
Done.
