### ISSUE TITLE
initial 'r' in Spanish mode is not turned into 'rr' 

### ISSUE THREAD

**Issue by heliosdrm** [arnog/tecendil-js#20]
Maybe related to this change in dd1a9368:

https://github.com/arnog/tecendil-js/blob/7f712c86415f689c182e11be28d30fe1b32cb0d8/modes/spanish.jsonc#L61

Initial 'r' should be turned into 'rr', such that it is displayed as rómen, instead of óre, but it does not work properly.

**Comment by heliosdrm** [comment]
bump

**Comment by heliosdrm** [comment]
Hi, is it possible to have this be fixed? Thanks!

**Comment by heliosdrm** [comment]
> Maybe related to this change in [dd1a936](https://github.com/arnog/tecendil-js/commit/dd1a93683ecfff645679d3582fd02a648b3145bc):
> 
> https://github.com/arnog/tecendil-js/blob/7f712c86415f689c182e11be28d30fe1b32cb0d8/modes/spanish.jsonc#L61
> 

Perhaps the problem is not the change in that line, but that the previous line was *not* changed?

https://github.com/arnog/tecendil-js/blob/7f712c86415f689c182e11be28d30fe1b32cb0d8/modes/spanish.jsonc#L60

Should the regular expression be put between slashes too? I.e.:
```
"/^r/": "rr",
```

**Comment by arnog** [comment]
The preprocess entries have to be either plain strings or regular expressions, the `^` in them is interpreted literally. For this to work, you have to use `"/^r/". I've updated the Spanish mode file accordingly.

**Comment by heliosdrm** [comment]
It works now. Thank you!
