### ISSUE TITLE
Built-in rules not working for consonants

### ISSUE THREAD

**Issue by alexander-koerschgen** [arnog/tecendil-js#45]
In https://github.com/arnog/tecendil-js/blob/master/modes/README.md it says

> There are 'built-in' rules for consonants and vowels that map single consonants and vowels to some common mapping, i.e. "p" to "{parma}", "a" to "[triple-dot-above]".

I have just started out with an essentially empty mode file (preprocess, map, words all empty objects). After dropping it into Tecendil, the built-in rules are working for consonants, but not for vowels. Consonants are simply left out, and all I get is vowels, each placed on a short vowel carrier.

**Comment by arnog** [comment]
Thanks. I have clarified that there are no built-in rules for consonants.
