### ISSUE TITLE
preprocess working just in first word, not in the whole sentence

### ISSUE THREAD

**Issue by b-runo** [arnog/tecendil-js#47]
I'm writing sentences now for test the mode file and the _preprocess_ rules are being apllied just in first word eg.:
Rule: 
`"/([aeiouà-ú])s([aeiouà-ú])/": "$1z$2"` // Letter S between vowels have the sound of Z

The entry in Tecendil:
`casa casa`

Give the following result:
![image](https://user-images.githubusercontent.com/18130367/182031378-8ab08d5b-31e2-4c66-ba53-1faee3730ea5.png)

I don't know if this behavior only happens when it's in test mode.

**Comment by arnog** [comment]
This is an issue that was introduced with the fix for preprocessing  of words with literal tengwa embedded in them.
I have pushed a fixed for this to tecendil.com
