### ISSUE TITLE
Change mode for the text "tecendil" used to show a preview of the fonts

### ISSUE THREAD

**Issue by shankarsivarajan** [arnog/tecendil-js#65]
In the font selection dropdown menu, the word "tecendil" next to the font name is always in the General Sindarin/English mode. It would be nice if that changed with the mode selected.

**Comment by arnog** [comment]
Hmmm... I'm nor sure. Tecendil *is* a Sindarin word, so it should be written with the Sindarin mode. But perhaps I could have a different word for each mode?

**Comment by WinstonSung** [comment]
> Tecendil *is* a Sindarin word

I would think that keep the Sindarin word written in Sindarin mode would be the better one, which is the current situation.

**Comment by heliosdrm** [comment]
> Tecendil _is_ a Sindarin word

Really? The suffix *-ndil* is a typically Quenya suffix (Elendil, etc.), and *tek-* is a Quenya verb stem too. I always took it as a Quenya word.

**Comment by arnog** [comment]
ah, yes, that’s a frequent point of confusion. The Tecendil website is named after the Grey Elf of the same name who was a renowned scholar admired for his calligraphy. His name was indeed Quenya in origin, but he wrote it using the Sindarin conventions. Hence the confusion.
