### ISSUE TITLE
Spaced “of the” shorthand replacement eating up words beginning with “the”

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#86]
The spaced version of the `“of the”` shorthand replacement (only present in _english.jsonc_) doesn’t take into account word boundaries and [will replace words](https://www.tecendil.com/?q=one%20of%20them%0Athoughts%20of%20therapists) starting with “the” following “of”.

So, “one of them” becomes `one <of-the>m`. “Thoughts of therapists” becomes “thoughts of the rapists"!

After a quick scan of most of the mode files, I believe this is the only example of a spaced `“word”` replacement.

**Comment by arnog** [comment]
Fixed
