### ISSUE TITLE
English Phonemic ignores line breaks

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#87]
I’ve got three issues with the processing of the English Phonemic mode that may all be related, but I’ll break them up just in case they are not.

This mode ignores line breaks.

If there is some limitation in the phonemic mode’s process that makes line breaks tricky, is one “solution” to add a line break literal? 

Haha, I really hope there is an easier solution than `{line-break}`!

**Comment by arnog** [comment]
Fixed
