### ISSUE TITLE
English Phonemic ignores word substitutions

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#89]
The English Phonemic mode is [ignoring](https://www.tecendil.com/?q=the%20of%20loch%20what%20for%20-%20the%27%20%27of%20%27loch%20what%27%20for%27%20-%20ofthe&mode=english-phonemic) all `"words"` substitutions if the word can be transcribed via the dictionary.

So “the” “of” and “and” don't trigger their shorthands as being normal English words they can be transcribed, whereas the spaceless non-word “ofthe” does trigger. 

All the rest of the `"words"` list fails as they are of course standard words, so no hwesta sindarinwa for “what”, “when”, “where”, etc.

All of these can be escaped by adding an apostrophe… if you know the word is meant to be substituted.

**Comment by arnog** [comment]
Fixed.
