### ISSUE TITLE
Phonemic hallelujah tehtar chaos

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#90]
English Phonemic goes a bit crazy when transcribing [hallelujah](https://www.tecendil.com/?q=hallelujah%20furuya%20alleluia&mode=english-phonemic).

The `/uːjə/` ending has a stray empty carrier followed by a fully loaded carrier with some confusing tehtar below: double dots for the following consonantal /y/ and an unutixe for the trailing schwa. Depending on the font this either ends up a mess of overlapping dots or looks confusingly like triple dots.

This can obviously be made clearer, even if it is just by offloading the curls and double dots to that empty carrier.

Non-expert musing ahead! I’m unfamiliar with any recent source texts, but I don’t believe the double dots are attested (though what is in this mode?!) so the carriers could be replaced with anna. Is the schwa’s unutixe meant to go under the preceding consonant in this mode? The only unutixe I know of is found in “return” under the óre and that sample is VC like this mode.

**Comment by arnog** [comment]
Fixed. Now splitting diacritics with more aggressive insertion of telcos.
