### ISSUE TITLE
Inconsistent spacing of pustas

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#93]
The pustas double through quintuple all render without their own spacing. Any spacing is user-supplied, just like every other tengwar character.

Single pusta is [always rendered](https://www.tecendil.com/?q=%3A.%2C%3A.%2C%0A%7Bpusta%7D%7Bdouble-pusta%7D%7Btriple-pusta%7D%7Bquadruple-pusta%7D%7Bquintuple-pusta%7D%7Bpusta%7D%7Bdouble-pusta%7D%7Btriple-pusta%7D%7Bquadruple-pusta%7D%7Bquintuple-pusta%7D) with a single space before it, none after.

I don’t know if this was intentional, but I think all the punctuation should be consistent.

My preference is no spacing so the user has full control and can replicate many Tolkien texts. I do understand why some prefer the opposite though, so that unexperienced users get a more typical presentation.

**Comment by arnog** [comment]
Fixed

**Comment by thirdofmarch** [comment]
Oh awesome; your solution to this was the best of both worlds!
