### ISSUE TITLE
Thúle can’t be capitalised

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#94]
While Telcontar has a capital thúle, it [can’t be rendered](https://www.tecendil.com/?q=Thin%20%7BTHUULE%7D%0AThan%20%7BANTO%7D%0AChin%20%7BCALMA%7D) by Tecendil in any mode.

There are no other issues with any other tengwar that represent a digraph… other than the usual hwesta sindarinwa, which of course has no capital in Telcontar yet.

The only other [capitalisation oddity](https://www.tecendil.com/?q=%7BSILME-NUQUERNA%7D%20%7BALT-SILME-NUQUERNA%7D) I spotted was `{alt-silme-nuquerna}`, which should just work as an alias to the regular silme in Telcontar.

**Comment by arnog** [comment]
Fixed
