### ISSUE TITLE
English mode: forced capitalisation of some "words"

### ISSUE THREAD

**Issue by thirdofmarch** [arnog/tecendil-js#95]
Is there still a need for the [forced capitalisation](https://www.tecendil.com/?q=alexander%20bach%20fernanda%20joel%20reuel%20tolkien%20zoe%0Aesther%20michael%20mikael%20tecendil%20thames%0AThomas%20%26%20thomas%0Acelebdil%20-%20cirth) of the handful of names under English modes `"words"` section now that Tecendil passes manual capitalisation on?

If not, then I believe that that link lists them all (Sindarin words just given as the range). The duplicate Thomas can also be removed.

**Comment by arnog** [comment]
Fixed.
